/** @file

    @copyright  @ref LIBAPPLICATION_LGPL_2_1,
                @n GNU Lesser General Public License

    @date       2021

    @author     Goetz Olbrischewski (goetz.olbrischewski@googlemail.com)

    @defgroup REF_AsmLicense app.AsmLicense
    @{
    @details  Class for logging license information provided by assembly.

    @ingroup  REF_libApplication
    @}
*/

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Reflection;
using System.Text;

namespace libApplication.app
{
/** @ingroup REF_AsmLicense

    @class   AsmLicense

    @brief   Class to log license information from License class
             generated by inline task during compilation.
*/
public class AsmLicense
    :   AsmInfo
    {
    public AsmLicense()
        :   base(".Generated.License")
        {
        }

    private static readonly List<string> the_basic_field_name_list = new List<string>
        {
            "short_text",
        };

    protected override void log_basic( FieldInfo[] field_info_list )
        {
        var basic_field_map = init_field_name_map(field_info_list, the_basic_field_name_list);
        var log_message = string.Empty;
        log_message += string.Format(CultureInfo.InvariantCulture, "{0}", basic_field_map["short_text"]);
        m_logger.info(0, log_message);
        }

    private static readonly List<string> the_extended_field_name_list = new List<string>
        {
            "long_text",
        };

    protected override void log_extended( FieldInfo[] field_info_list )
        {
        var extended_field_map = init_field_name_map(field_info_list, the_extended_field_name_list);
        var log_message = string.Empty;
        log_message += string.Format(CultureInfo.InvariantCulture, "{0}", extended_field_map["long_text"]);
        m_logger.info(0, log_message);
        }
    }
}
