//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("libApplication.Properties.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die app_config must not be a null value. ähnelt.
        /// </summary>
        internal static string APP_CONFIG_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("APP_CONFIG_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die args and arg_table must not be null values. ähnelt.
        /// </summary>
        internal static string ARGS_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("ARGS_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Argument assembly must not be a null value. ähnelt.
        /// </summary>
        internal static string ASSEMBLY_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("ASSEMBLY_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Argument build_type_name  must not be an empty string or null value. ähnelt.
        /// </summary>
        internal static string BUILD_TYPE_NAME_EXCEPTION {
            get {
                return ResourceManager.GetString("BUILD_TYPE_NAME_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display build information. ähnelt.
        /// </summary>
        internal static string BUILDINFO_EXCEPTION {
            get {
                return ResourceManager.GetString("BUILDINFO_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Directory &apos;{0}&apos; does not exist or is not accessible. ähnelt.
        /// </summary>
        internal static string DIRECTORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("DIRECTORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Argument entry must not be a null value. ähnelt.
        /// </summary>
        internal static string ENTRY_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("ENTRY_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caught exception: {0} ähnelt.
        /// </summary>
        internal static string EXCEPTION {
            get {
                return ResourceManager.GetString("EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Argument field_info_list must not be a null value. ähnelt.
        /// </summary>
        internal static string FIELD_INFO_LIST_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("FIELD_INFO_LIST_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Argument field_name_list must not be a null value. ähnelt.
        /// </summary>
        internal static string FIELD_NAME_LIST_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("FIELD_NAME_LIST_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Argument field_name must not be an empty string or null value. ähnelt.
        /// </summary>
        internal static string FIELD_NAME_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("FIELD_NAME_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filename &apos;{0}&apos; does not exist or is not accessible. ähnelt.
        /// </summary>
        internal static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Binary number &apos;{0}&apos; contains invalid digits. ähnelt.
        /// </summary>
        internal static string FORMAT_INVALID_BINARY_DIGITS {
            get {
                return ResourceManager.GetString("FORMAT_INVALID_BINARY_DIGITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Binary numbers must start with &apos;0b&apos; prefix. ähnelt.
        /// </summary>
        internal static string FORMAT_INVALID_BINARY_PREFIX {
            get {
                return ResourceManager.GetString("FORMAT_INVALID_BINARY_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decimal number &apos;{0}&apos; contains invalid digits. ähnelt.
        /// </summary>
        internal static string FORMAT_INVALID_DECIMAL_DIGITS {
            get {
                return ResourceManager.GetString("FORMAT_INVALID_DECIMAL_DIGITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hexadecimal number &apos;{0}&apos; contains invalid digits. ähnelt.
        /// </summary>
        internal static string FORMAT_INVALID_HEXADECIMAL_DIGITS {
            get {
                return ResourceManager.GetString("FORMAT_INVALID_HEXADECIMAL_DIGITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hexadecimal numbers must start with &apos;0x&apos; prefix. ähnelt.
        /// </summary>
        internal static string FORMAT_INVALID_HEXADECIMAL_PREFIX {
            get {
                return ResourceManager.GetString("FORMAT_INVALID_HEXADECIMAL_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Octal number &apos;{0}&apos; contains invalid digits. ähnelt.
        /// </summary>
        internal static string FORMAT_INVALID_OCTAL_DIGITS {
            get {
                return ResourceManager.GetString("FORMAT_INVALID_OCTAL_DIGITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Octal numbers must start with &apos;0&apos; prefix. ähnelt.
        /// </summary>
        internal static string FORMAT_INVALID_OCTAL_PREFIX {
            get {
                return ResourceManager.GetString("FORMAT_INVALID_OCTAL_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display version and build information. ähnelt.
        /// </summary>
        internal static string HELP_BUILD_INFO {
            get {
                return ResourceManager.GetString("HELP_BUILD_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display help message. ähnelt.
        /// </summary>
        internal static string HELP_HELP_INFO {
            get {
                return ResourceManager.GetString("HELP_HELP_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display license and version information. ähnelt.
        /// </summary>
        internal static string HELP_LICENSE_INFO {
            get {
                return ResourceManager.GetString("HELP_LICENSE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase verbose level. ähnelt.
        /// </summary>
        internal static string HELP_VERBOSITY_INFO {
            get {
                return ResourceManager.GetString("HELP_VERBOSITY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid value for short_arg and long_arg. ähnelt.
        /// </summary>
        internal static string INVALID_ARG_NAME_EXCEPTION {
            get {
                return ResourceManager.GetString("INVALID_ARG_NAME_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid datestamp format, could not parse datetime string &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string INVALID_DATE_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help text must not be a an emty string or null and have at least one character ending with &apos;.&apos;. ähnelt.
        /// </summary>
        internal static string INVALID_HELP_TEXT_EXCEPTION {
            get {
                return ResourceManager.GetString("INVALID_HELP_TEXT_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid option &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string INVALID_OPTION_EXCEPTION {
            get {
                return ResourceManager.GetString("INVALID_OPTION_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The real number format is invalid &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string INVALID_REAL_NUMBER_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_REAL_NUMBER_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die short_arg must be a digit, letter or 0x00. ähnelt.
        /// </summary>
        internal static string INVALID_SHORT_ARG_EXCEPTION {
            get {
                return ResourceManager.GetString("INVALID_SHORT_ARG_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display license information. ähnelt.
        /// </summary>
        internal static string LICENSE_EXCEPTION {
            get {
                return ResourceManager.GetString("LICENSE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die long_arg is reserverd for application or was already used. ähnelt.
        /// </summary>
        internal static string LONG_ARG_EXCEPTION {
            get {
                return ResourceManager.GetString("LONG_ARG_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Argument &apos;{0}&apos; is mandatory. ähnelt.
        /// </summary>
        internal static string MANDATORY_ARG_EXCEPTION {
            get {
                return ResourceManager.GetString("MANDATORY_ARG_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Option &apos;{0}&apos; must not have an argument. ähnelt.
        /// </summary>
        internal static string NO_ARGUMENT_EXCEPTION {
            get {
                return ResourceManager.GetString("NO_ARGUMENT_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Numeric value for parameter &apos;{0}&apos; is not in range [{1}..{2}]. ähnelt.
        /// </summary>
        internal static string NUMBER_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("NUMBER_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot parse null or empty string value to a number. ähnelt.
        /// </summary>
        internal static string NUMBER_PARSE_NULL {
            get {
                return ResourceManager.GetString("NUMBER_PARSE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Option string may not be an empty string or null value. ähnelt.
        /// </summary>
        internal static string OPTION_STR_EXCEPTION {
            get {
                return ResourceManager.GetString("OPTION_STR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Option string does not match the expected unit type {0}. ähnelt.
        /// </summary>
        internal static string OPTION_SYMBOL_EXCEPTION {
            get {
                return ResourceManager.GetString("OPTION_SYMBOL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Argument param must not be a null value. ähnelt.
        /// </summary>
        internal static string PARAM_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("PARAM_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Option &apos;{0}&apos; must have an argument. ähnelt.
        /// </summary>
        internal static string REQUIRED_ARGUMENT_EXCEPTION {
            get {
                return ResourceManager.GetString("REQUIRED_ARGUMENT_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die short_arg is reserverd for application or was already used. ähnelt.
        /// </summary>
        internal static string SHORT_ARG_EXCEPTION {
            get {
                return ResourceManager.GetString("SHORT_ARG_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Symbol argument may not be a null or empty string value. ähnelt.
        /// </summary>
        internal static string SYMBOL_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("SYMBOL_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TimeValue  &apos;{0}&apos; has unparsable format. ähnelt.
        /// </summary>
        internal static string TIME_VALUE_FORMAT {
            get {
                return ResourceManager.GetString("TIME_VALUE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unhandled ArgType for option &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string UNHANDLED_ARG_TYPE_EXCEPTION {
            get {
                return ResourceManager.GetString("UNHANDLED_ARG_TYPE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display usage information. ähnelt.
        /// </summary>
        internal static string USAGE_EXCEPTION {
            get {
                return ResourceManager.GetString("USAGE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Argument initial value string must not be a null value. ähnelt.
        /// </summary>
        internal static string VALUE_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("VALUE_NULL_EXCEPTION", resourceCulture);
            }
        }
    }
}
