//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("libApplication.Properties.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_config must not be a null value..
        /// </summary>
        internal static string APP_CONFIG_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("APP_CONFIG_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to args and arg_table must not be null values..
        /// </summary>
        internal static string ARGS_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("ARGS_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument assembly must not be a null value..
        /// </summary>
        internal static string ASSEMBLY_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("ASSEMBLY_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument build_type_name  must not be an empty string or null value..
        /// </summary>
        internal static string BUILD_TYPE_NAME_EXCEPTION {
            get {
                return ResourceManager.GetString("BUILD_TYPE_NAME_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display build information..
        /// </summary>
        internal static string BUILDINFO_EXCEPTION {
            get {
                return ResourceManager.GetString("BUILDINFO_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; does not exist or is not accessible..
        /// </summary>
        internal static string DIRECTORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("DIRECTORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument entry must not be a null value..
        /// </summary>
        internal static string ENTRY_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("ENTRY_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caught exception: {0}.
        /// </summary>
        internal static string EXCEPTION {
            get {
                return ResourceManager.GetString("EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument field_info_list must not be a null value..
        /// </summary>
        internal static string FIELD_INFO_LIST_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("FIELD_INFO_LIST_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument field_name_list must not be a null value..
        /// </summary>
        internal static string FIELD_NAME_LIST_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("FIELD_NAME_LIST_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument field_name must not be an empty string or null value..
        /// </summary>
        internal static string FIELD_NAME_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("FIELD_NAME_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename &apos;{0}&apos; does not exist or is not accessible..
        /// </summary>
        internal static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary number &apos;{0}&apos; contains invalid digits..
        /// </summary>
        internal static string FORMAT_INVALID_BINARY_DIGITS {
            get {
                return ResourceManager.GetString("FORMAT_INVALID_BINARY_DIGITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary numbers must start with &apos;0b&apos; prefix..
        /// </summary>
        internal static string FORMAT_INVALID_BINARY_PREFIX {
            get {
                return ResourceManager.GetString("FORMAT_INVALID_BINARY_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal number &apos;{0}&apos; contains invalid digits..
        /// </summary>
        internal static string FORMAT_INVALID_DECIMAL_DIGITS {
            get {
                return ResourceManager.GetString("FORMAT_INVALID_DECIMAL_DIGITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal number &apos;{0}&apos; contains invalid digits..
        /// </summary>
        internal static string FORMAT_INVALID_HEXADECIMAL_DIGITS {
            get {
                return ResourceManager.GetString("FORMAT_INVALID_HEXADECIMAL_DIGITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal numbers must start with &apos;0x&apos; prefix..
        /// </summary>
        internal static string FORMAT_INVALID_HEXADECIMAL_PREFIX {
            get {
                return ResourceManager.GetString("FORMAT_INVALID_HEXADECIMAL_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octal number &apos;{0}&apos; contains invalid digits..
        /// </summary>
        internal static string FORMAT_INVALID_OCTAL_DIGITS {
            get {
                return ResourceManager.GetString("FORMAT_INVALID_OCTAL_DIGITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octal numbers must start with &apos;0&apos; prefix..
        /// </summary>
        internal static string FORMAT_INVALID_OCTAL_PREFIX {
            get {
                return ResourceManager.GetString("FORMAT_INVALID_OCTAL_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display version and build information..
        /// </summary>
        internal static string HELP_BUILD_INFO {
            get {
                return ResourceManager.GetString("HELP_BUILD_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display help message..
        /// </summary>
        internal static string HELP_HELP_INFO {
            get {
                return ResourceManager.GetString("HELP_HELP_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display license and version information..
        /// </summary>
        internal static string HELP_LICENSE_INFO {
            get {
                return ResourceManager.GetString("HELP_LICENSE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase verbose level..
        /// </summary>
        internal static string HELP_VERBOSITY_INFO {
            get {
                return ResourceManager.GetString("HELP_VERBOSITY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for short_arg and long_arg..
        /// </summary>
        internal static string INVALID_ARG_NAME_EXCEPTION {
            get {
                return ResourceManager.GetString("INVALID_ARG_NAME_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid datestamp format, could not parse datetime string &apos;{0}&apos;..
        /// </summary>
        internal static string INVALID_DATE_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help text must not be a an emty string or null and have at least one character ending with &apos;.&apos;..
        /// </summary>
        internal static string INVALID_HELP_TEXT_EXCEPTION {
            get {
                return ResourceManager.GetString("INVALID_HELP_TEXT_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option &apos;{0}&apos;..
        /// </summary>
        internal static string INVALID_OPTION_EXCEPTION {
            get {
                return ResourceManager.GetString("INVALID_OPTION_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The real number format is invalid &apos;{0}&apos;..
        /// </summary>
        internal static string INVALID_REAL_NUMBER_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_REAL_NUMBER_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to short_arg must be a digit, letter or 0x00..
        /// </summary>
        internal static string INVALID_SHORT_ARG_EXCEPTION {
            get {
                return ResourceManager.GetString("INVALID_SHORT_ARG_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display license information..
        /// </summary>
        internal static string LICENSE_EXCEPTION {
            get {
                return ResourceManager.GetString("LICENSE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to long_arg is reserverd for application or was already used..
        /// </summary>
        internal static string LONG_ARG_EXCEPTION {
            get {
                return ResourceManager.GetString("LONG_ARG_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; is mandatory..
        /// </summary>
        internal static string MANDATORY_ARG_EXCEPTION {
            get {
                return ResourceManager.GetString("MANDATORY_ARG_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; must not have an argument..
        /// </summary>
        internal static string NO_ARGUMENT_EXCEPTION {
            get {
                return ResourceManager.GetString("NO_ARGUMENT_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric value for parameter &apos;{0}&apos; is not in range [{1}..{2}]..
        /// </summary>
        internal static string NUMBER_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("NUMBER_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option string may not be an empty string or null value..
        /// </summary>
        internal static string OPTION_STR_EXCEPTION {
            get {
                return ResourceManager.GetString("OPTION_STR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option string does not match the expected unit type {0}..
        /// </summary>
        internal static string OPTION_SYMBOL_EXCEPTION {
            get {
                return ResourceManager.GetString("OPTION_SYMBOL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument param must not be a null value..
        /// </summary>
        internal static string PARAM_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("PARAM_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; must have an argument..
        /// </summary>
        internal static string REQUIRED_ARGUMENT_EXCEPTION {
            get {
                return ResourceManager.GetString("REQUIRED_ARGUMENT_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to short_arg is reserverd for application or was already used..
        /// </summary>
        internal static string SHORT_ARG_EXCEPTION {
            get {
                return ResourceManager.GetString("SHORT_ARG_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol argument may not be a null or empty string value..
        /// </summary>
        internal static string SYMBOL_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("SYMBOL_NULL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeValue  &apos;{0}&apos; has unparsable format..
        /// </summary>
        internal static string TIME_VALUE_FORMAT {
            get {
                return ResourceManager.GetString("TIME_VALUE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled ArgType for option &apos;{0}&apos;..
        /// </summary>
        internal static string UNHANDLED_ARG_TYPE_EXCEPTION {
            get {
                return ResourceManager.GetString("UNHANDLED_ARG_TYPE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display usage information..
        /// </summary>
        internal static string USAGE_EXCEPTION {
            get {
                return ResourceManager.GetString("USAGE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument initial value string must not be a null value..
        /// </summary>
        internal static string VALUE_NULL_EXCEPTION {
            get {
                return ResourceManager.GetString("VALUE_NULL_EXCEPTION", resourceCulture);
            }
        }
    }
}
